### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#1]
MTZlZmFhMzkyNGE2ZmQ5ZDNhNDg4MDA5OWE0YWM2NWQ= is the metadata hash I am seeing in the debugger.

It should be 32 bytes

in Assetexample  on this line
            tx = Utils.GetConfigAssetTransaction(acct2.Address, assetID, ap, transParams, "config trans");

**Comment by RileyGe** [comment]
I already fix this bug in commit [0d28e35b493d0ddf309226947b3feaaed0dc24f4](https://github.com/RileyGe/dotnet-algorand-sdk/commit/0d28e35b493d0ddf309226947b3feaaed0dc24f4)
