### ISSUE TITLE
Error NodeStatus and cannot be null using on algoexplorer api

### ISSUE THREAD

**Issue by karpediemnow** [RileyGe/dotnet-algorand-sdk#10]
Hi,
I'm trying to use the c# algorand sdk on algoexplorer api (https://api.testnet.algoexplorer.io/)

and I have the following error:
catchupTime is a required property for NodeStatus and cannot be null

How can I solve this issue?

Thanks!

**Comment by RileyGe** [comment]
give me the code.

**Comment by karpediemnow** [comment]
`using Algorand.Algod.Api;
using Algorand.Algod.Model;
using System;
using System.Net;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string ALGOD_API_ADDR = "https://api.testnet.algoexplorer.io/";
                string ALGOD_API_TOKEN = null;

                AlgodApi algodApiInstance = new AlgodApi(ALGOD_API_ADDR, ALGOD_API_TOKEN);
                NodeStatus status = algodApiInstance.GetStatus();
                Console.WriteLine($"Algorand network status ({algodApiInstance.Configuration.BasePath}): " + status.ToJson());
            }
            catch (Exception ex)
            {                
                Console.WriteLine(ex.Message);  //Kaboom--> catchupTime is a required property for NodeStatus and cannot be null
            }

            Console.ReadKey();
        }
    }
}
`

**Comment by RileyGe** [comment]
First, you need to know which version API did you want to use. In the code you posted, you are using the API v1.

Second, you use the wrong ALGOD_API_ADDR and ALGOD_API_TOKEN. The right ALGOD_API_ADDR should like "https://testnet-algorand.api.purestake.io/ps1" and every user have a different ALGOD_API_TOKEN. Please find these on "https://developer.purestake.io/home"

**Comment by karpediemnow** [comment]
Try to call:
curl -X GET "https://api.algoexplorer.io/v1/status" -H  "accept: application/json"

or run 
`using Algorand.Algod.Api;
using Algorand.Algod.Model;
using Algorand.Client;
using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string ALGOD_API_ADDR = "https://api.testnet.algoexplorer.io/";

            string ALGOD_API_TOKEN = null;


            try
            {
                #region HttpClient

                HttpClient client = new HttpClient();

                var msg = client.GetStringAsync($"{ALGOD_API_ADDR}v1/status").Result;

                Console.WriteLine("\n HttpClient:\n" + msg);

                #endregion
            }
            catch (Exception ex)
            {
                Console.WriteLine($"\n HttpClient: {ex.Message}");// OK!

            }


            try
            {
                #region AlgodApi
                AlgodApi algodApiInstance = new AlgodApi(ALGOD_API_ADDR, ALGOD_API_TOKEN);

                NodeStatus status = algodApiInstance.GetStatus();
                Console.WriteLine($"\n Algorand network status \n {status.ToJson()}");
                #endregion
            }
            catch (Exception ex)
            {                
                Console.WriteLine($"\nAlgodApi: \n{ex.Message}");//Kabbom -> catchupTime is a required property for NodeStatus and cannot be null
            }


            Console.ReadKey();
        }
    }
}
`
