### ISSUE TITLE
waitfortransaction

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#13]
The utils needs an update for the waitfortransaction function so that it returns the pending transaction response and has the following parms and functionality referenced in this sample Java code. https://github.com/algorand-devrel/hackathon/blob/master/algorandsamples/v2/java-test/src/main/java/com/algorand/javatest/firsttransaction/NoteField.java , Also all samples need to be updated to call this method after a raw submit.

**Comment by RileyGe** [comment]
Sure, I will update the code this week.

**Comment by RileyGe** [comment]
The function in this issue is actually implemented in the Algorand.Utils.WaitTransactionToComplete function. And in the example I wrote, I also wrote an example in V2/BasicExample.cs (line 78).

**Comment by rfustino** [comment]
Ya, I saw it in Utils, as well as called in the v2/basicexample. but it needs updated to return the pending tx, and provide a  third param for the maximum number of blocks to look at, and some other error handling on pool errors. The Java sample attached is accurate on all those fronts.  So, the call to waitfortransaction would change too and not have to look up the pending tx as it is returned now. The other SDKs are going to make waitforconformation as part of the SDK, just not sure on the implementation. They make make it a parameter to wait, ie client.RawTransaction(txn).Do(true), Regardless, all V2 examples need the call to waitforconfirmation after the call to Utils.SubmitTransaction and modified for the additional param and logic.

**Comment by RileyGe** [comment]
Understood, I already updated the SDK and update the examples.

**Comment by rfustino** [comment]
Looks good, can you please test with PureStake on TestNet and see if it works without a timeout error? I think the waitforblock will throttle it down to the limit of 5 requests per second. This is for the new method public static PendingTransactionResponse WaitTransactionToComplete(...), if not, we may need to put the sleep back in the loop at the bottom. Much appreciated.

**Comment by RileyGe** [comment]
I have been using Purestake to test my code, which can run correctly in Purestake. Your worry is correct and there will be no problems. Because the `instance.WaitForBlock` method is called in the loop. The average block time of Algorand is 4 seconds. So each cycle takes about 4 seconds.
