### ISSUE TITLE
algodApiInstance.AccountInformationAsync missing fields in response

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#15]
The Amount field is not returned among other fields in the response for algodApiInstance.AccountInformationAsync ... they are in the non-async call however algodApiInstance.AccountInformation. 
 
Without Async
![image](https://user-images.githubusercontent.com/4959925/105891714-f011aa00-5fde-11eb-8613-d9616543f9a4.png)

Async:
![image](https://user-images.githubusercontent.com/4959925/105891759-fe5fc600-5fde-11eb-8387-23b3ba036129.png)

The synchronous call returns Algorand.V2.Model.Account and the asynchronous call tries to return Algorand.Account
![image](https://user-images.githubusercontent.com/4959925/105895603-b55e4080-5fe3-11eb-954b-e95b81950a25.png)

here are my using statements
 ```
using Algorand;
using Algorand.V2;
using Algorand.Client;
using Algorand.V2.Model;
using Account = Algorand.Account;
using Transaction = Algorand.Transaction;```

**Comment by RileyGe** [comment]
Updated the SDK to fix this issue, also add an example to https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/AccountTest.cs

**Comment by rfustino** [comment]
Can you please check all of the other async calls in the SDK? For example the getBlockAsync, for example in https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/BasicExample.cs , should this work the same way?  We need async for mobile apps.

**Comment by RileyGe** [comment]
The problem in the previous code is due to the misuse of the `Algorand.Account` class and `Algorand.V2.Model.Account`. I checked all classes with the same name and found no other similarities.
