### ISSUE TITLE
rekey example missing

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#16]
Unless I am missing it. we need a rekey example too. I see it is in the SDK, but it would be very helpful to include that with the V2 examples.

**Comment by RileyGe** [comment]
Do we have any rekey example of java SDK? I searched the example but cannot find one.

**Comment by RileyGe** [comment]
I find a python example [Python Rekey Example](https://github.com/algorand-devrel/hackathon/blob/c9aedc6d60ebd65bfbe01e9cf3fb446440be0a55/algorandsamples/v2/mypythondemo/rekey/rekey.py) and write the csharp example: [Csharp Rekey Example](https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/RekeyExample.cs)

**Comment by rfustino** [comment]
Perfect that is the link i was going to send you on Rekey in Python. I need to do the other languages yet. Thanks!
