### ISSUE TITLE
Stateful contact debugging sample needed

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#18]
We also need a stateful contract lifecycle example that creates a dryrun (in a different way than the existing dry run samples)  to debug. Follow this example in python. Obviously we do not need the pyteal part of this, just start with reading an existing teal file to debug. https://github.com/algorand-devrel/hackathon/blob/master/algorandsamples/v2/mypythondemo/pyteal/pyteal_dryrun_stateful_debugger.py

**Comment by RileyGe** [comment]
This is a huge project for me, especially if I don't know much about teal programming and debugging, I will spend time to understand how to do it and slowly this example completely. I will write it separately in the form of a tutorial after the SDK is completed. But we do need an example of SDK interaction with stateful contracts, so I will add an example similar to [Java Stateful Contract Example](https://github.com/algorand-devrel/hackathon/blob/master/algorandsamples/v2/java-test/src/main/java/com/algorand/javatest/smart_contracts/StatefulSmartContract.java). I will leave this issue open until I finished the tutorial.

**Comment by RileyGe** [comment]
I already update the example on [DryrunStatefulExample.cs](https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/contract/DryrunStatefulExample.cs)
