### ISSUE TITLE
Langspec.json needs to be read from dll not filesystem.

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#19]
This is a bug, on langspec.json ... we need to read this from memory , not from the file system. We did that once before. When i build a mobile device, it crashes cause it can't find it for stateful contracts. It is not as easy as just copying it over like you can do in the console apps, this needs to be deployed in ios , making it difficult.

Temp fix for console apps when getting error, cannot find langspec.json in sdk-examples folder, copy it there and it works. However, this is more complicated in ios and android apps. We made this fix before. This is happening in StatefulContract.cs and CompileTEAL.cs. please check elsewhere. 

![image](https://user-images.githubusercontent.com/4959925/111364989-507ca980-8668-11eb-8a30-3612b7ab9f61.png)

![image](https://user-images.githubusercontent.com/4959925/111365033-5c686b80-8668-11eb-8f8b-0cf080c7fb4a.png)

**Comment by RileyGe** [comment]
Yes, you are right. I went through the code again and I found two-position use this file, but last time I only changed one of them. I already updated the code in the commit: https://github.com/RileyGe/dotnet-algorand-sdk/commit/b0198cd1ca5a80335bc71ef24a4ca13c789781d3. The code should be ok, please try again.
