### ISSUE TITLE
langspec.json not found

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#2]
Either the location of langspec.json needs to be changed or the code needs to be changed to find this file from logic.cs.

The code is looking for it in the sdk-samples folder.

![2020-01-08_23-14-01](https://user-images.githubusercontent.com/4959925/72038372-2fa01380-326f-11ea-812d-7b44dcfd41da.png)

![2020-01-08_23-17-56](https://user-images.githubusercontent.com/4959925/72038396-3d559900-326f-11ea-8c5e-778bac830227.png)

**Comment by RileyGe** [comment]
I did not have this question on my windows computer, but I update the langspec.json proprety and fix this problem. Can you please try again to find if this question is fixed.

**Comment by rfustino** [comment]
yes, this is fixed. Thanks.
