### ISSUE TITLE
Tealdbg sample

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#20]
Need a sample using tealdbg command from the code? create a new sample calling the teal debugger, similar to what is done in the call app method in python. The dryrun file is created differently for that purpose. https://github.com/algorand-devrel/hackathon/blob/master/algorandsamples/v2/mypythondemo/pyteal/pyteal_dryrun_stateful_debugger.py

**Comment by RileyGe** [comment]
I already write an example similar to https://github.com/algorand-devrel/hackathon/blob/master/algorandsamples/v2/mypythondemo/pyteal/pyteal_dryrun_stateful_debugger.py, you can find it on https://github.com/RileyGe/dotnet-algorand-sdk/blob/master/sdk-examples/V2/contract/DryrunStatefulExample.cs. I tested it and it work fine.
