### ISSUE TITLE
{"message":"Forbidden"} on  Get status call

### ISSUE THREAD

**Issue by chsami** [RileyGe/dotnet-algorand-sdk#21]
I keep getting this error:

Algorand.Client.ApiException: Error calling GetStatus: {"message":"Forbidden"}

This is how my code looks like:
 
```
   string ALGOD_API_ADDR = "https://testnet-algorand.api.purestake.io"; //find in algod.net

  AlgodApi algodApiInstance = new AlgodApi(ALGOD_API_ADDR, ALGOD_API_TOKEN);
  var status = algodApiInstance.GetStatus();
```

**Comment by RileyGe** [comment]
I believe you are using the wrong API address, it's usually like https://testnet-algorand.api.purestake.io/ps2
