### ISSUE TITLE
Manage asset does not work with Purestake node - missing authentication token

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#22]
Getting missing authentication token error on manage asset call, create asset works fine. Hackathon and local instance work fine too.
![image](https://user-images.githubusercontent.com/4959925/112068739-ee78e400-8b40-11eb-9193-6520ff858023.png)
![image](https://user-images.githubusercontent.com/4959925/112068745-f2a50180-8b40-11eb-85b8-e7a4e3776c80.png)
![image](https://user-images.githubusercontent.com/4959925/112068752-f6d11f00-8b40-11eb-8337-f1be9232e4cb.png)

Looks like it might be in `DefaultAPI.cs` in the 
`public ApiResponse< Asset > GetAssetByIDWithHttpInfo (long? assetId)` method

**Comment by Vytek** [comment]
I have the same Issue:

ApiException: Error calling GetAssetByID: {"message":"Missing Authentication Token"}
Algorand.V2.Algod.DefaultApi.GetAssetByIDWithHttpInfo (System.Nullable`1[T] assetId) (at <a44c0c3341c04590a6d895fd922f0bc3>:0)
Algorand.V2.Algod.DefaultApi.GetAssetByID (System.Nullable`1[T] assetId) (at <a44c0c3341c04590a6d895fd922f0bc3>:0)
AlgorandManager.ModifyAsset (System.String AlgodURLEndpoint, System.String AlgodToken, System.String AssetName, System.String AssetUnitName, System.Nullable`1[T] TotalAssetCount, System.Nullable`1[T] AssetDecimals, System.String AssetURL, System.String AssetmetadataHash, System.String AssetTxMessage, System.Nullable`1[T] AssetID) (at Assets/AlgorandUnitySDK/Scripts/AlgorandManager.cs:702)
StartAssetGame.Start () (at Assets/AlgorandUnitySDK/Scenes/Scripts/StartAssetGame.cs:50)

**Comment by RileyGe** [comment]
Please refer: #11 
The purestake moved some functions from algod to indexer. 
Please find more information from (https://developer.purestake.io/v1deprecation)[https://developer.purestake.io/v1deprecation]

**Comment by RileyGe** [comment]
If you want to query the assets information using purestake, please use indexer instead.

**Comment by Vytek** [comment]
![image](https://user-images.githubusercontent.com/2614303/118390673-9934ec80-b630-11eb-9f9d-fd83d819c3dc.png)

Yes, also check on https://developer.purestake.io/apis

Please @rfustino Close this issue ;-)

@RileyGe Thank you very much!
