### ISSUE TITLE
Metadata hash should be able to be longer than 32 bytes when base 64 encoded?

### ISSUE THREAD

**Issue by johanstenberg92** [RileyGe/dotnet-algorand-sdk#23]
Hi,

When I'm trying to create a new asset, I put a SHA-256 hash as the metadata hash. This hash is 32 bytes. This needs to be base64 encoded while sent over the wire.

The SDK should be able to handle this. Now also there's a requirement in the code that the V2 AssetParams should be 32 bytes, when base64 encoded. As I understand it, this is an unnecessary requirement. And also, it also puts an unnecessary concern on which hash algorithm you should use (you might need to shorten it -> you lose entropy).

**Comment by Vytek** [comment]
This field is 32 Byte in the protocol:

See https://developer.algorand.org/docs/reference/transactions/#asset-parameters

MetaDataHash | optional | []byte | "am" | This field is intended to be a 32-byte hash of some metadata that is relevant to your asset and/or asset holders. The format of this metadata is up to the application. This field can&nbsp;only&nbsp;be specified upon creation. An example might be the hash of some certificate that acknowledges the digitized asset as the official representation of a particular real-world asset.

**Comment by johanstenberg92** [comment]
Yes, I know. But let’s say I have some media, and I hash it, I use SHA-256. I get 32 bytes. Now that’s what I want on the blockchain. But using the .NET SDK I need to base-64 encode those bytes, then send it over the wire, then I assume they are base54 decoded. The problem is that if I base64 encode it, it might be another size than exactly 32 bytes.

**Comment by RileyGe** [comment]
I agree with @Vytek, this is a limitation of Algorand, and there is no way to achieve it through the SDK. I also encountered this problem before. My approach is to reduce the length of the hash so that it just reaches 32 bytes after base64 encoding.

**Comment by johanstenberg92** [comment]
Let me try to validate my statement above using the REST API? If I can’t make it work we can just close the issue.

**Comment by johanstenberg92** [comment]
Actually now I realize that it must be not decoded from Base64 otherwise the SDK wouldn’t work. You are right @RileyGe. So as you state the problem lies in the node implementation not in the sdk.
