### ISSUE TITLE
No FlatFee support in V2?

### ISSUE THREAD

**Issue by johanstenberg92** [RileyGe/dotnet-algorand-sdk#24]
Hi,

Doesn't seem to be any flat fee support in V2?

Thanks,

Johan

**Comment by johanstenberg92** [comment]
Again learning stuff, you can after you have created the payment transaction modify the `fee` field to set the flat fee. Not very documented but possible.

**Comment by johanstenberg92** [comment]
But, this way is counter-intuitive. @rfustino FYI. Should there be an effort to add this in the SDK?

**Comment by RileyGe** [comment]
Is flatfee very commonly used? If it is very common, I can directly add a convenient method to accomplish this. But too many convenient methods will also increase the cost of learning.

**Comment by johanstenberg92** [comment]
I think it's worthwhile to add it, the other SDKs support it. That said I agree with the general philosophy not to bloat. Thanks Riley

**Comment by rfustino** [comment]
Nice find @johanstenberg92 . Yes, @RileyGe it would be good to be consistent to the other SDKs.

**Comment by RileyGe** [comment]
https://github.com/RileyGe/dotnet-algorand-sdk/commit/ea118be734a8dbf67a059e4601fe8fd4e1474ce2
