### ISSUE TITLE
Add method to export private key and recreate Algorand Account from exported private key (New features)

### ISSUE THREAD

**Issue by Vytek** [RileyGe/dotnet-algorand-sdk#26]
https://github.com/RileyGe/dotnet-algorand-sdk/blob/6afcac017eb116876f9f42b4d3fd8fdebd3cea79/dotnet-algorand-sdk/Account.cs#L95

You can only export Mnemonic BIP39 to re-create  Algorand Account.

Please add a new method to export private key (ED25519) and re-create account from export private key. Like:

```
Account _Account = new Account();
_Account.GetClearTextEd25519PrivateKey();

// Similar to:  public byte[] GetClearTextPublicKey()
//https://github.com/RileyGe/dotnet-algorand-sdk/blob/6afcac017eb116876f9f42b4d3fd8fdebd3cea79/dotnet-algorand-sdk/Account.cs#L68
```
and re-create:

`
Account _Account = new Account(PrivateKey)
`

It is very important to save privatekey in secure vault or DPAPI (https://docs.microsoft.com/it-it/dotnet/api/system.security.cryptography.protecteddata?view=net-5.0)

Thank you!

**Comment by Vytek** [comment]
```
/// <summary>
/// Convenience method for getting the underlying private key for raw operations.
/// </summary>
/// <returns>the private key as length 32 byte array.</returns>
public byte[] GetClearTextPrivateKey()
{
    var privateKey = privateKeyPair.Private as Ed25519PrivateKeyParameters;

    byte[] b = privateKey.GetEncoded(); // X.509 prepended with ASN.1 prefix

    if (b.Length != SK_SIZE)
    {
        throw new Exception("Generated private key is the wrong size");
    }
    return b;
}
```
Is it a possible method?

**Comment by RileyGe** [comment]
> ```
> /// <summary>
> /// Convenience method for getting the underlying private key for raw operations.
> /// </summary>
> /// <returns>the private key as length 32 byte array.</returns>
> public byte[] GetClearTextPrivateKey()
> {
>     var privateKey = privateKeyPair.Private as Ed25519PrivateKeyParameters;
> 
>     byte[] b = privateKey.GetEncoded(); // X.509 prepended with ASN.1 prefix
> 
>     if (b.Length != SK_SIZE)
>     {
>         throw new Exception("Generated private key is the wrong size");
>     }
>     return b;
> }
> ```
> 
> Is it a possible method?

Yes, this is the solution, and I will find out a way to recover an account from private key.

**Comment by RileyGe** [comment]
fix this in https://github.com/RileyGe/dotnet-algorand-sdk/commit/9f52063712b2eae9415054b78cb8ce5d9b702c72

**Comment by RileyGe** [comment]
I add a static method `AccountFromPrivateKey` to re-create the account from privatekey.

**Comment by Vytek** [comment]
Thank you very much!
