### ISSUE TITLE
Getting error on indexer lookup block

### ISSUE THREAD

**Issue by rfustino** [RileyGe/dotnet-algorand-sdk#30]
Process is terminating due to StackOverflowException.
The target process exited with code 0 (0x00000000) while evaluating the function 'Algorand.V2.Model.StateSchema.ToString'.
The program '[71215] sdk-examples.dll' has exited with code 0 (0x0).

```            System.Threading.Thread.Sleep(1200); //test in purestake, imit 1 req/sec
            long block = 16958571;
            var blockInfo = indexer.LookupBlock(block);
            Console.WriteLine("Look up block " + blockInfo.ToJson());  ```

**Comment by rfustino** [comment]
More info
![2021-09-29_15-50-02](https://user-images.githubusercontent.com/4959925/135338689-abd5e36c-7d72-498e-9b24-37cd8ec28957.png)

**Comment by Dayjay** [comment]
I think the JSON Property Names are wrong, I submit a pull request asap. Below is your code with the adjusted names when I tested them:

![grafik](https://user-images.githubusercontent.com/25659168/135466116-8e3dc5f7-c781-46b2-8fca-d945a17f2799.png)
