### ISSUE TITLE
fix asa creation

### ISSUE THREAD

**Issue by scholtz** [RileyGe/dotnet-algorand-sdk#35]
hi, i have created pull request #33 

@RileyGe can you please commit it to the code and create new version in nuget so that we dont have to have full project cloned next to our project please?

the protocol has been upgraded and the nft standard requres the address to be approx 70 char long

**Comment by Vytek** [comment]
Hello, I have created a fork with all pull requests. Please see: https://github.com/Vytek/dotnet-algorand-sdk

**Comment by Vytek** [comment]
https://github.com/Vytek/dotnet-algorand-sdk/releases/tag/0.2.0.9

**Comment by RileyGe** [comment]
Already merged request #33
